// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAaUgyJ_rDPepyJXdsyyyhjaHl9Mmolo',
    appId: '1:551498612682:web:afb605bc8aba30fe531933',
    messagingSenderId: '551498612682',
    projectId: 'fateen7-f6bc3',
    authDomain: 'fateen7-f6bc3.firebaseapp.com',
    storageBucket: 'fateen7-f6bc3.firebasestorage.app',
    measurementId: 'G-W123M5X68K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjsStMadQdsnr2OHjCeewgrjGi2tGjAV4',
    appId: '1:551498612682:android:cb09c6e5edbafd9d531933',
    messagingSenderId: '551498612682',
    projectId: 'fateen7-f6bc3',
    storageBucket: 'fateen7-f6bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFoaraCLm4QpfiImUdPPXgoQW3KlQ2Di8',
    appId: '1:551498612682:ios:dde06232853201a6531933',
    messagingSenderId: '551498612682',
    projectId: 'fateen7-f6bc3',
    storageBucket: 'fateen7-f6bc3.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFoaraCLm4QpfiImUdPPXgoQW3KlQ2Di8',
    appId: '1:551498612682:ios:dde06232853201a6531933',
    messagingSenderId: '551498612682',
    projectId: 'fateen7-f6bc3',
    storageBucket: 'fateen7-f6bc3.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTAaUgyJ_rDPepyJXdsyyyhjaHl9Mmolo',
    appId: '1:551498612682:web:55463b86f18388d3531933',
    messagingSenderId: '551498612682',
    projectId: 'fateen7-f6bc3',
    authDomain: 'fateen7-f6bc3.firebaseapp.com',
    storageBucket: 'fateen7-f6bc3.firebasestorage.app',
    measurementId: 'G-R4QYBQJ7HB',
  );
}
