name: fateen
description: "A new Flutter project."
publish_to: "none"

version: 6.0.0+16

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # تحديث الاعتماديات المتعارضة
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0 # تحديد إصدار بدلاً من "any"
  firebase_auth: ^5.4.2

  uuid: ^4.5.1
  syncfusion_flutter_charts: ^29.1.33
  file_picker: ^9.0.0
  http: ^1.0.0 # تحديث من 0.13.0 إلى 1.0.0
  firebase_core: ^3.12.1
  plugin_platform_interface: ^2.1.8
  pigeon: ^24.2.2
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.2.0 # تحديد إصدار بدلاً من "any"
  intl: ^0.19.0
  flutter_drawing_board: ^0.9.5
  flutter_local_notifications: ^18.0.1
  syncfusion_flutter_pdf: ^29.1.33
  cloud_firestore: ^5.6.4
  provider: ^6.1.2
  share_plus: ^10.1.4
  google_mlkit_translation: ^0.12.0
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.9
  permission_handler: ^11.4.0
  flutter_slidable: ^4.0.0
  percent_indicator: ^4.2.4
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.0
  image_editor: ^1.6.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  animate_do: ^4.2.0
  # إضافة lottie بإصدار متوافق
  lottie: ^3.1.3
  # تعديل إصدار flutter_native_splash
  flutter_native_splash: ^2.4.5
  timer_count_down: ^2.2.2
  audioplayers: ^6.4.0
  url_launcher: ^6.3.1
  printing: ^5.14.2
  hijri: ^3.0.0
  theme_provider: ^0.6.0
  flutter_colorpicker: ^1.1.0
  perfect_freehand: ^2.3.2
  flutter_tesseract_ocr: ^0.4.28
  loading_animation_widget: ^1.3.0
  flutter_animate: ^4.5.2
  motion_toast: ^2.12.1
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.3
  flutter_spinkit: ^5.2.1
  awesome_dialog: ^3.2.1
  confetti: ^0.8.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  flutter_neumorphic: ^3.2.0
  firebase_storage: ^12.4.5
  card_swiper: ^3.0.1
  universal_html: ^2.2.4
  open_file: ^3.5.10
  flutter_image_compress: ^2.4.0
  google_mlkit_text_recognition: ^0.14.0
  firebase_app_check: ^0.3.2+5
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# إضافة قسم لتجاوز الإصدارات المتعارضة إذا لزم الأمر
dependency_overrides:
  http: ^1.0.0
  archive: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SYMBIOAR+LT
      fonts:
        - asset: fonts/SYMBIOAR+LT-REGULAR.TTF
